### ISSUE TITLE
Virtual Power Meter for GPU-intensive tasks

### ISSUE THREAD

**Issue by xzyaoi** [daviddao/green-ai#1]
I recently learned that deep learning costs us too much power and produced much carbon dioxide, and I want to measure how much power I have consumed. But I have not found a software that could measure it. Therefore I built a very tiny python package to measure it to remind such information. Hope it could be helpful for others, and therefore I hope this could be added to this repository as part of practices to aware developers about the power consumption, though it is not as accurate as physical measurements.

Here it is: https://autoai-incubator.github.io/powermeter/

**Comment by daviddao** [comment]
That is so so cool!!! Thanks for contributing. I'm more than happy to add this into the repository.

**Comment by xzyaoi** [comment]
Thanks so much! :)
